// Deterministic static catalog build. Existing public URLs are retained.
const fs=require('node:fs');
const path=require('node:path');
const products=require('../data/catalog.json');
const families=require('../data/families.cjs');
families.push({id:'whoop',name:'WHOOP MG Life 5.0',brand:'whoop',model:'MG Life',generation:5,route:'/whoop-mg-life/',description:{ru:'Фитнес-браслет без экрана с членством Life на 12 месяцев. Отслеживание сна, нагрузки и восстановления; медицинские функции зависят от региона, аккаунта и совместимости.',uz:'Life a’zoligi 12 oyga kiritilgan ekransiz fitnes bilaguzuk. Uyqu, yuklama va tiklanish kuzatuvi; ayrim funksiyalar hududga bog‘liq.'}});
const origin='https://www.techgeek.uz';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const write=(p,s)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s)};
const priceText=p=>p.price===null?'$???':'$'+p.price;
const variants=f=>products.filter(p=>p.family===f.id).sort((a,b)=>(a.price??Infinity)-(b.price??Infinity)||a.variant.localeCompare(b.variant));
const sorted=[...families].sort((a,b)=>(a.id==='whoop')-(b.id==='whoop')||(variants(a)[0].price??Infinity)-(variants(b)[0].price??Infinity)||a.name.localeCompare(b.name));
const tr=(ru,uz)=>`data-ru="${e(ru)}" data-uz="${e(uz)}"`;
const options=(f,id)=>variants(f).map(p=>`<option value="${p.id}" ${p.id===id?'selected':''}>${e(p.variant)} · ${e(p.size||'Life 12 months')} — ${priceText(p)}</option>`).join('');
const arrow='<svg class="icon-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M5 19 19 5M5 5h14v14"/></svg>';
const note={ru:'Под заказ, на складе нет. Заявка не является оплатой или подтверждённой покупкой. Возможность поставки, срок и итоговую сумму в сумах согласуем до оформления.',uz:'Buyurtma asosida, omborda yo‘q. So‘rov to‘lov yoki tasdiqlangan xarid emas. Yetkazish imkoniyati, muddati va so‘mdagi yakuniy summa oldindan kelishiladi.'};
function card(f,i){const p=variants(f)[0];return `<article class="product-card" data-category="${p.category}" data-family="${f.id}" data-brand="${f.brand}" data-generation="${f.generation}" data-min-price="${p.price??''}" data-product-id="${p.id}">
 <a class="product-picture ${p.id==='whoop'?'whoop-picture':''}" href="${e(p.url.ru)}" data-product-link="${p.id}"><span class="stock-label" ${tr('Под заказ','Buyurtma asosida')}>Под заказ</span><span class="product-index">${String(i+1).padStart(2,'0')}</span><img src="${p.image}" alt="${e(p.name+' '+p.variant)}" width="1000" height="716" loading="lazy" decoding="async"><span class="picture-arrow">${arrow}</span></a>
 <div class="product-info"><div class="product-kicker">${e(f.brand==='meta'?'META GLASSES':f.brand.toUpperCase())}${f.generation&&p.category==='glasses'?' · GEN '+f.generation:''}</div><h3 class="product-name"><a href="${e(p.url.ru)}" data-product-link="${p.id}">${e(f.name)}</a></h3><p ${tr(f.description.ru,f.description.uz)}>${e(f.description.ru)}</p>
 <label class="variant-label"><span ${tr('Цвет, линзы и размер','Rang, linza va o‘lcham')}>Цвет, линзы и размер</span><select class="variant-select" data-variant-select="${f.id}" aria-label="${e(f.name)}: вариант">${options(f,p.id)}</select></label>
 <div class="product-buy"><div><strong data-price="${p.id}">${priceText(p)}</strong><span ${tr('за одно устройство','bitta qurilma uchun')}>за одно устройство</span></div><button type="button" data-add="${p.id}" class="add-button"><span ${tr('В заявку','So‘rovga')}>В заявку</span><span aria-hidden="true">+</span></button></div></div></article>`}
let catalog=fs.readFileSync('catalog.js','utf8');
catalog=catalog.replace(/  \/\/ (?:Retail prices|US Meta Store snapshot)[\s\S]*?\]\.map\(function \(product\) \{/,`  // US Meta Store snapshot + $30 per glasses SKU. All products are on request.\n  const products = ${JSON.stringify(products,null,2)}.map(function (product) {`);
// Subsequent builds replace only the generated data block.
if(!catalog.includes('sourceCheckedAt'))throw Error('Catalog data block missing');
catalog=catalog.replace('"Здравствуйте! Хочу заказать на TechGeek.uz:"','"Здравствуйте! Прошу подтвердить поставку под заказ на TechGeek.uz:"').replace('"Salom! TechGeek.uz saytidan buyurtma bermoqchiman:"','"Salom! TechGeek.uz orqali buyurtma asosida yetkazishni tasdiqlang:"');
write('catalog.js',catalog);
let homepage=fs.readFileSync('index.html','utf8');
homepage=homepage.replace(/<div class="catalog-refine">[\s\S]*?(?=<p id="currencyNote")/,'').replace(/\s*<script src="\/catalog-ui.js" defer><\/script>/g,'').replace(/\s*<link rel="stylesheet" href="\/catalog.css"\s*\/>/g,'');
homepage=homepage.replace(/<div class="product-grid" id="productsGrid">[\s\S]*?(?=<div class="catalog-footnote">)/,`<div class="product-grid" id="productsGrid">${sorted.map(card).join('\n')}</div><p id="filterStatus" role="status" aria-live="polite"></p>\n        `);
homepage=homepage.replace(/<div class="filter-tabs"[\s\S]*?(?=<div class="currency-switch")/,`<div class="filter-tabs" aria-label="Категории товаров"><button data-filter="all" aria-pressed="true" ${tr('Все устройства','Barcha qurilmalar')}>Все устройства</button><button data-filter="glasses" aria-pressed="false" ${tr('Умные очки','Aqlli ko‘zoynaklar')}>Умные очки</button><button data-filter="fitness" aria-pressed="false" ${tr('Фитнес-браслеты','Fitnes bilaguzuklar')}>Фитнес-браслеты</button></div>`);
homepage=homepage.replace(/<p id="currencyNote"[^>]*><\/p>/,`<div class="catalog-refine"><label><span ${tr('Линейка','Turkum')}>Линейка</span><select id="catalogBrand"><option value="all" ${tr('Все линейки','Barcha turkumlar')}>Все линейки</option><option value="rayban">Ray-Ban Meta</option><option value="oakley">Oakley Meta</option><option value="meta">Meta Glasses</option><option value="display">Meta Ray-Ban Display</option><option value="whoop">WHOOP</option></select></label><label><span ${tr('Поколение','Avlod')}>Поколение</span><select id="catalogGeneration"><option value="all" ${tr('Все','Barchasi')}>Все</option><option value="1">Gen 1</option><option value="2">Gen 2</option></select></label><label><span ${tr('Порядок','Tartib')}>Порядок</span><select id="catalogSort"><option value="default" ${tr('По моделям: от доступных','Modellar: arzonidan')}>По моделям: от доступных</option><option value="asc" ${tr('Цена по возрастанию','Narx: o‘sish')}>Цена по возрастанию</option><option value="desc" ${tr('Цена по убыванию','Narx: kamayish')}>Цена по убыванию</option></select></label></div><p class="order-notice" ${tr(note.ru,note.uz)}>${note.ru}</p><p id="currencyNote" class="currency-note" aria-live="polite"></p>`);
homepage=homepage.replace(/Три устройства, которые хочется носить каждый день\. Все — в наличии,\s*с гарантией\./g,'Умные очки и носимые гаджеты. Выберите модель, цвет и размер — привезём под заказ.').replace(/Har kuni taqishni istaydigan uchta qurilma\. Barchasi mavjud, kafolat bilan\./g,'Aqlli ko‘zoynaklar va gadjetlar. Model, rang va o‘lchamni tanlang — buyurtma asosida yetkazamiz.');
homepage=homepage.replace(/(<script type="application\/ld\+json">)([\s\S]*?)(<\/script>)/,(m,a,json,z)=>{const d=JSON.parse(json);d['@graph']=d['@graph'].filter(n=>n['@type']!=='FAQPage');const list=d['@graph'].find(n=>n['@type']==='ItemList');Object.assign(list,{name:'Каталог TechGeek.uz — под заказ',numberOfItems:families.length,itemListElement:sorted.map((f,i)=>({'@type':'ListItem',position:i+1,url:origin+f.route,name:f.name}))});return a+JSON.stringify(d,null,2)+z});
homepage=homepage.replace('<script src="/storefront.js" defer></script>','<script src="/storefront.js" defer></script>\n<script src="/catalog-ui.js" defer></script>').replace('<link rel="stylesheet" href="/styles.css" />','<link rel="stylesheet" href="/styles.css" />\n<link rel="stylesheet" href="/catalog.css" />');
write('index.html',homepage);
const base=fs.readFileSync('ray-ban-meta-gen-1-clear/index.html','utf8');
const header=base.slice(base.indexOf('<body'),base.indexOf('<main')).trimEnd();
const footer=base.slice(base.indexOf('<footer'),base.indexOf('<script src="/catalog.js"')).trimEnd();
function page(f,lang,route,only){const uz=lang==='uz';const list=only?[only]:variants(f);const p=list[0];const t=(ru,uzText)=>uz?uzText:ru;const title=only?p.name+' '+p.variant:f.name;
 const schema={'@context':'https://schema.org','@graph':[{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'TechGeek.uz',item:origin+'/'},{'@type':'ListItem',position:2,name:t('Умные очки','Aqlli ko‘zoynaklar'),item:origin+'/smart-glasses/'},{'@type':'ListItem',position:3,name:title,item:origin+route}]},...list.map(v=>({'@type':'Product',name:v.name+' '+v.variant+' · '+(v.size||''),sku:v.sku,...(v.gtin?{gtin:v.gtin}:{}),image:origin+v.image,description:f.description[lang],brand:{'@type':'Brand',name:v.name.startsWith('Oakley')?'Oakley':v.name.startsWith('Ray-Ban')?'Ray-Ban':v.id==='whoop'?'WHOOP':'Meta'},offers:{'@type':'Offer',url:origin+(only?route:v.url[lang]),price:v.price,priceCurrency:'USD',availability:'https://schema.org/OutOfStock',shippingDetails:{'@type':'OfferShippingDetails',shippingRate:{'@type':'MonetaryAmount',value:0,currency:'USD'},shippingDestination:{'@type':'DefinedRegion',addressCountry:'UZ'}}}}))]};
 const lensSpec=t('Заводские линзы, без индивидуальных диоптрий. Transitions — фотохромные, Polar / Polarized — поляризационные; Prizm — технология Oakley.','Zavod linzalari, individual dioptriyasiz. Transitions — fotoxrom, Polar / Polarized — qutblangan; Prizm — Oakley texnologiyasi.');
 const isGen1=f.generation===1;const tech=f.id==='whoop'?t('Отслеживание сна, нагрузки и восстановления. Life на 12 месяцев.','Uyqu, yuklama va tiklanish. Life 12 oy.'):f.id==='display'?t('Дисплей в линзе; Neural Band. Требуется отдельное согласование комплектации.','Linzadagi displey; Neural Band. To‘plam alohida kelishiladi.'):isGen1?t('Камера 12 МП, HD-видео, открытые динамики; до 4 часов работы на одном заряде.','12 MP kamera, HD video, ochiq dinamiklar; bir zaryadda 4 soatgacha.'):['adventurer','starfire','wayfarer-gen-2'].includes(f.id)?t('Камера 12 МП, видео до 3K/30. Открытый звук; '+(f.brand==='meta'?'более 8 часов':'до 8 часов')+' работы (данные производителя, зависит от использования).','12 MP kamera, 3K/30 gacha video, ochiq ovoz; taxminan 8 soat ishlash, foydalanishga bog‘liq.'):t('Камера для фото и видео, открытые динамики, управление через совместимый смартфон и Meta AI.','Foto va video kamerasi, ochiq dinamiklar, mos smartfon va Meta AI orqali boshqaruv.');
 return `<!doctype html><html lang="${lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} — ${t('под заказ в Ташкенте','Toshkentda buyurtma asosida')} | TechGeek.uz</title><meta name="description" content="${e(f.description[lang])}"><link rel="canonical" href="${origin+route}"><link rel="alternate" hreflang="ru" href="${origin+route.replace(/^\/uz\//,'/')}"><link rel="alternate" hreflang="uz" href="${origin+'/uz'+route.replace(/^\/uz\//,'/')}"><meta property="og:title" content="${e(title)}"><meta property="og:image" content="${origin+p.image}"><link rel="icon" href="/favicon.png"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/product-page.css"><link rel="stylesheet" href="/catalog.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head>${header}
 <main class="product-page-main" id="inner-main"><nav class="container breadcrumbs"><a href="/">TechGeek.uz</a> / <a href="/smart-glasses/">${t('Каталог очков','Ko‘zoynaklar')}</a> / <span>${e(title)}</span><a href="${uz?route.replace(/^\/uz\//,'/'):'/uz'+route}" lang="${uz?'ru':'uz'}">${uz?'RU':'UZ'}</a></nav><section class="product-landing-hero"><div class="container product-landing-grid" data-product-detail data-family="${f.id}"><div class="product-gallery"><img data-detail-image src="${p.image}" alt="${e(p.name+' '+p.variant)}" width="1000" height="716" fetchpriority="high"></div><div class="product-landing-copy"><span class="product-status">${t('Под заказ · на складе нет','Buyurtma asosida · omborda yo‘q')}</span><h1>${e(title)}</h1><p class="product-lead">${e(f.description[lang])}</p><label class="variant-label">${t('Цвет, штатные линзы и размер','Rang, standart linza va o‘lcham')}<select class="variant-select" data-variant-select="${f.id}">${only?`<option value="${p.id}">${e(p.variant)} · ${e(p.size||'Life 12 months')} — ${priceText(p)}</option>`:options(f,p.id)}</select></label><div class="product-price"><strong data-detail-price>${priceText(p)}</strong><span>${t('розничная цена','chakana narx')}</span></div><p class="retail-note">${note[lang]}</p><p data-source-status>${t('Возможность закупки конкретного варианта проверим перед подтверждением.','Tanlangan variantni xarid qilish imkoniyati tasdiqlashdan oldin tekshiriladi.')}</p><div class="product-actions"><a data-detail-order class="btn btn-primary" href="/?add=${p.id}&amp;lang=${lang}">${t('Добавить в заявку','So‘rovga qo‘shish')} ${arrow}</a><a class="btn btn-secondary" href="https://t.me/techgeek_uz">Telegram</a></div><p><a href="tel:+998992999900">+998 99 299 99 00</a></p></div></div></section>
 <section class="content-band"><div class="container"><h2>${t('Особенности модели','Model xususiyatlari')}</h2><dl class="spec-list"><div class="spec-item"><dt>${t('Технологии','Texnologiyalar')}</dt><dd>${tech}</dd></div><div class="spec-item"><dt>${t('Посадка','Moslashuv')}</dt><dd>${e([...new Set(list.map(v=>v.size||'Life 12 months'))].join(' / '))}</dd></div><div class="spec-item"><dt>${t('Линзы и комплектация','Linzalar va to‘plam')}</dt><dd>${p.category==='glasses'?lensSpec:t('Браслет MG и членство Life на 12 месяцев.','MG bilaguzuk va Life a’zoligi 12 oy.')}</dd></div><div class="spec-item"><dt>${t('Гарантия','Kafolat')}</dt><dd>${t('Подлинность и 1 месяц на заводской брак.','Asllik va zavod nuqsoniga 1 oy kafolat.')}</dd></div></dl><p>${t('Meta AI, языки и отдельные функции зависят от страны, аккаунта, приложения и версии ПО. Не обещаем доступность всех функций в Узбекистане.','Meta AI, tillar va ayrim funksiyalar hudud, hisob, ilova va dasturga bog‘liq. O‘zbekistonda barcha funksiyalar ishlashi kafolatlanmaydi.')}</p><p class="source-note">${t('Цены очков: Meta Store US + $30. Сверено','Ko‘zoynak narxi: Meta Store US + $30. Tekshirildi')} ${products[0].sourceCheckedAt.slice(0,10)}. ${p.source?`<a data-detail-source href="${e(p.source)}" rel="noopener nofollow" target="_blank">Meta Store</a>`:''}</p></div></section>
 <section class="content-band alt"><div class="container"><h2>${t('Варианты и цены','Variantlar va narxlar')}</h2><div class="variant-table-wrap"><table class="variant-table"><thead><tr><th>${t('Вариант','Variant')}</th><th>${t('Размер','O‘lcham')}</th><th>USD</th></tr></thead><tbody>${list.map(v=>`<tr><td><a href="${e(v.url[lang])}">${e(v.variant)}</a></td><td>${e(v.size||'Life 12 months')}</td><td>${priceText(v)}</td></tr>`).join('')}</tbody></table></div><p>${t('Все варианты — под заказ. Поставка начинается только после согласования; оплаты на сайте нет.','Barcha variantlar buyurtma asosida. Yetkazish kelishuvdan keyin boshlanadi; saytda to‘lov yo‘q.')}</p></div></section><section class="content-band"><div class="container"><h2>${t('Другие модели','Boshqa modellar')}</h2><div class="related-models">${sorted.filter(x=>x.id!==f.id&&x.brand===f.brand).map(x=>`<a href="${uz?'/uz':''}${x.route}">${e(x.name)}</a>`).join('')}<a href="/smart-glasses/">${t('Все умные очки','Barcha aqlli ko‘zoynaklar')}</a><a href="${uz?'/uz/yetkazib-berish-va-kafolat/':'/dostavka-i-garantiya/'}">${t('Доставка и гарантия','Yetkazish va kafolat')}</a></div></div></section></main>${footer}<script src="/catalog.js" defer></script><script src="/catalog-ui.js" defer></script><script src="/analytics.js" defer></script></body></html>`;
}
function finalPage(f,lang,route,p){
 let html=page(f,lang,route,p);
 if(f.id==='display')html=html.replace(/<p class="source-note">[\s\S]*?<\/p>/,`<p class="source-note">${lang==='uz'?'Narx so‘rov bo‘yicha. Joriy narx buyurtmadan oldin kelishiladi.':'Цена по запросу. Актуальная стоимость согласовывается перед оформлением.'}</p>`).replace('розничная цена','цена по запросу').replace('chakana narx','narx so‘rov bo‘yicha');
 const opposite=lang==='uz'?route.replace(/^\/uz\//,'/'):'/uz'+route;
 html=html.replace(/href="\/uz\/ray-ban-meta-gen-1-clear\/"\s+class="lang-btn"\s+lang="uz"\s+aria-label="O‘zbekcha versiya"\s*>UZ/,`href="${opposite}" class="lang-btn" lang="${lang==='uz'?'ru':'uz'}" aria-label="${lang==='uz'?'Русская версия':'O‘zbekcha versiya'}">${lang==='uz'?'RU':'UZ'}`);
 if(lang==='uz')html=html.replace(/Перейти к содержимому/g,'Asosiy mazmunga o‘tish').replace(/Основная навигация/g,'Asosiy navigatsiya').replace(/>Позвонить</g,'>Qo‘ng‘iroq qilish<').replace(/>Каталог</g,'>Katalog<').replace(/>Доставка и гарантия</g,'>Yetkazish va kafolat<').replace(/>Конфиденциальность</g,'>Maxfiylik<').replace(/Принимаем\s*заказы 24\/7/g,'Buyurtmalar 24/7 qabul qilinadi');
 if(f.id==='whoop')html=html.replace(/<p class="source-note">[\s\S]*?<\/p>/,`<p class="source-note">${lang==='uz'?'Life a’zoligi — 12 oy. Narx va yetkazish muddati buyurtmadan oldin tasdiqlanadi.':'Членство Life — 12 месяцев. Цену и срок поставки подтверждаем до оформления.'}</p>`).replace(/href="\/smart-glasses\/">Каталог очков/g,'href="/#catalog">Каталог техники').replace(/href="\/smart-glasses\/">Ko‘zoynaklar/g,'href="/#catalog">Qurilmalar');
 if(f.id==='vanguard')html=html.replace('</dl>',`<div class="spec-item"><dt>${lang==='uz'?'Sport uchun':'Для спорта'}</dt><dd>${lang==='uz'?'IP67; odatiy foydalanishda 9 soatgacha. Garmin va Strava integratsiyasi mos qurilma va xizmatlarni talab qiladi.':'IP67; до 9 часов обычного использования. Интеграция Garmin и Strava требует совместимых устройств и сервисов.'}</dd></div></dl>`);
 if(['blayzer-gen-2','scriber-gen-2'].includes(f.id))html=html.replace('</dl>',`<div class="spec-item"><dt>${lang==='uz'?'Gardish':'Оправа'}</dt><dd>${lang==='uz'?'Almashtiriladigan burun tayanchlari va optik sozlaydigan quloq uchlari. Retsept linzalari bu taklifga kirmaydi.':'Сменные носоупоры, регулируемые оптиком заушники и шарниры с дополнительным раскрытием. Рецептурные линзы в это предложение не входят.'}</dd></div></dl>`);
 html=html.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/,(match,json)=>{
  const data=JSON.parse(json);if(f.id==='display')data['@graph'].forEach(n=>{delete n.offers;});const vs=data['@graph'].filter(n=>n['@type']==='Product');
  if(f.id==='whoop')Object.assign(data['@graph'][0].itemListElement[1],{name:lang==='uz'?'Fitnes bilaguzuklar':'Фитнес-браслеты',item:origin+'/#catalog'});
  if(!p&&f.id!=='whoop'){
   vs.forEach(v=>{v['@id']=origin+route+'#'+v.sku;v.isVariantOf={'@id':origin+route+'#group'};const product=products.find(x=>x.sku===v.sku);v.size=product.size;v.color=product.color||product.variant;});
   data['@graph'].push({'@type':'ProductGroup','@id':origin+route+'#group',productGroupID:f.id,name:f.name,description:f.description[lang],url:origin+route,variesBy:['https://schema.org/color','https://schema.org/size'],hasVariant:vs.map(v=>({'@id':v['@id']}))});
  }
  return '<script type="application/ld+json">'+JSON.stringify(data).replace(/</g,'\\u003c')+'</script>';
 });
 return html;
}
for(const f of families)for(const lang of ['ru','uz']){const route=(lang==='uz'?'/uz':'')+f.route;write(route.slice(1)+'index.html',finalPage(f,lang,route));}
for(const id of ['clear','chameleon']){const p=products.find(x=>x.id===id);const f=families.find(x=>x.id===p.family);for(const lang of ['ru','uz'])write(p.url[lang].slice(1)+'index.html',finalPage(f,lang,p.url[lang],p));}
// A real category hub; family pages, not one SEO page per color/size.
for(const lang of ['ru','uz']){const uz=lang==='uz';const route=(uz?'/uz':'')+'/smart-glasses/';const title=uz?'Aqlli ko‘zoynaklar':'Умные очки';write(route.slice(1)+'index.html',`<!doctype html><html lang="${lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Meta, Ray-Ban, Oakley | TechGeek.uz</title><meta name="description" content="${title}: Gen 1, Gen 2, Oakley, Meta Glasses, Display. ${uz?'Buyurtma asosida':'Под заказ в Ташкенте и Узбекистане'}."><link rel="canonical" href="${origin+route}"><link rel="alternate" hreflang="ru" href="${origin}/smart-glasses/"><link rel="alternate" hreflang="uz" href="${origin}/uz/smart-glasses/"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/catalog.css"></head><body><header class="container"><a href="/" class="logo">TechGeek.uz</a></header><main class="container category-hub"><h1>${title}</h1><p>${note[lang]}</p>${['rayban','meta','oakley','display'].map(brand=>`<section><h2>${{rayban:'Ray-Ban Meta',meta:'Meta Glasses',oakley:'Oakley Meta',display:'Meta Ray-Ban Display'}[brand]}</h2><div class="product-grid">${sorted.filter(f=>f.brand===brand).map((f,i)=>{const p=variants(f)[0];return `<article class="product-card"><a class="product-picture" href="${uz?'/uz':''}${f.route}"><img src="${p.image}" width="1000" height="716" loading="lazy" alt="${e(f.name)}"></a><div class="product-info"><h3><a href="${uz?'/uz':''}${f.route}">${e(f.name)}</a></h3><p>${e(f.description[lang])}</p><strong>${p.price===null?'':uz?'Dan':'От'} ${priceText(p)}</strong></div></article>`}).join('')}</div></section>`).join('')}<a href="/#catalog">${uz?'Barcha qurilmalar':'Все устройства'}</a></main>${footer}</body></html>`)}
// On-request enquiries are not confirmed purchases: no invented dispatch date.
const feed=products.filter(p=>p.price!==null).map(p=>`<item><g:id>${e(p.sku)}</g:id><g:title>${e(p.name+' '+p.variant)}</g:title><g:description>${e('Под заказ, на складе нет. Возможность поставки и срок подтверждаются до оформления. '+p.variant)}</g:description><g:link>${e(origin+p.url.ru)}</g:link><g:image_link>${origin+p.image}</g:image_link><g:condition>new</g:condition><g:availability>out_of_stock</g:availability><g:price>${p.price.toFixed(2)} USD</g:price>${p.gtin?`<g:gtin>${p.gtin}</g:gtin>`:'<g:identifier_exists>false</g:identifier_exists>'}<g:shipping><g:country>UZ</g:country><g:service>Delivery after confirmation</g:service><g:price>0.00 USD</g:price></g:shipping></item>`).join('\n');
write('merchant-feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss xmlns:g="http://base.google.com/ns/1.0" version="2.0"><channel><title>TechGeek.uz</title><link>${origin}</link><description>Catalog on request</description>${feed}</channel></rss>\n`);
function htmlFiles(dir=''){return fs.readdirSync(dir||'.',{withFileTypes:true}).flatMap(x=>x.name.startsWith('.')||['node_modules','scripts','tests','data'].includes(x.name)?[]:x.isDirectory()?htmlFiles(path.join(dir,x.name)):x.name.endsWith('.html')?[path.join(dir,x.name)]:[])}
const urls=htmlFiles().map(file=>{const s=fs.readFileSync(file,'utf8');return /<link\s+rel="canonical"\s+href="([^"]+)"/.exec(s)?.[1]}).filter(Boolean);
// Record meaningful editorial changes without refreshing every URL on each build.
const editorialDates = { [origin + '/']: '2026-09-21' };
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...new Set(urls)].map(url=>`<url><loc>${url}</loc><lastmod>${editorialDates[url] || products[0].sourceCheckedAt.slice(0,10)}</lastmod></url>`).join('')}</urlset>\n`);
console.log('Built '+families.length+' model pages per language, '+products.length+' SKUs.');
require('./migrate-order-copy.cjs');
require('./polish-storefront.cjs');
